//
//  CreateOrderInteractor.swift
//  ViperExample
//
//  Created by Amit kumar Swami on 09/01/16.
//  Copyright (c) 2016 Aks. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol CreateOrderInteractorInput {
    var shippingMethods: [String] { get }
    func formatExpirationDate(request: CreateOrder_FormatExpirationDate_Request)
    func doSomething(request: CreateOrderRequest)
}

protocol CreateOrderInteractorOutput {
    func presentExpirationDate(response: CreateOrder_FormatExpirationDate_Response)
    func presentSomething(response: CreateOrderResponse)
}

class CreateOrderInteractor: CreateOrderInteractorInput {
    var output: CreateOrderInteractorOutput!
    var worker: CreateOrderWorker!
    var shippingMethods = [
        "Standard Shipping",
        "Two-Day Shipping ",
        "One-Day Shipping "
    ]
    
    func formatExpirationDate(request: CreateOrder_FormatExpirationDate_Request) {
        let response = CreateOrder_FormatExpirationDate_Response(date: request.date)
        output.presentExpirationDate(response)
    }
    
    // MARK: Business logic
    
    func doSomething(request: CreateOrderRequest)
    {
        // NOTE: Create some Worker to do the work
        
        worker = CreateOrderWorker()
        worker.doSomeWork()
        
        // NOTE: Pass the result to the Presenter
        
        let response = CreateOrderResponse()
        output.presentSomething(response)
    }
}
